[package]
name = "sphinx-proof"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sphinx-proof"
path = "sphinx-proof/main.rs"

[dependencies]
sphinx-sdk = { git = "https://github.com/argumentcomputer/sphinx", branch = "dev", features = ["plonk"] }
hex = "0.4.3"
sha2 = "0.9"
itertools = "0.12.1"
