[package]
name = "plonk-core"
version = "1.0.82"

[addresses]
plonk_verifier_addr = '_'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
